import { requirePageSession } from "@/lib/auth/session.ts";
import { runtimeEnv } from "@/lib/auth/config.ts";
import { readDetail, readSnapshot, requestDetail } from "@/lib/dashboard/store.ts";
import DashboardShell from "../../dashboard-shell.tsx";
import PendingDetail from "../../pending-detail.tsx";
import StoryActions from "../../story-actions.tsx";
import { dateTime, fullDateTime, number, records, text } from "../../presentation.ts";

export const dynamic = "force-dynamic";

export default async function StoryDetail({ params }: { params: Promise<{ id: string }> }) {
  const session = await requirePageSession(["master"]);
  const { id } = await params;
  const source = runtimeEnv();
  const stored = await readSnapshot(source.DB);
  const story = stored?.snapshot.stories.find((item) => String(item.id) === id) || await readDetail(source.DB, "story", id);
  if (!story && stored?.bridgeConnected) await requestDetail(source.DB, { resourceType: "story", resourceId: id, requestedBy: session.actorId });
  if (!story) return <DashboardShell active="inbox" eyebrow="Story detail" title="Fetching story" intro="Historical details are requested from the laptop only when needed.">{stored?.bridgeConnected ? <PendingDetail label="Retrieving the full story, evidence, and history" /> : <section className="data-panel"><h2>Detail unavailable while offline</h2><p className="empty-state">The story index remains cached, but this historical detail was not retained. Wake the laptop and reload.</p></section>}</DashboardShell>;
  const sources = records(story, "sources");
  const claims = records(story, "claims");
  const evidence = records(story, "evidence_sources");
  const priority = text(story, "priority", "Standard");
  return <DashboardShell active="inbox" eyebrow="Story detail" title="" intro="" customHeader>
    <nav className="breadcrumb" aria-label="Breadcrumb"><a href="/dashboard/inbox">News inbox</a><span>›</span><span>{id}</span></nav>
    <header className="story-hero"><div className="story-hero-copy"><div className="eyebrow-row"><span className={`tag tag-${text(story, "freshness", "older").toLowerCase()}`}>{text(story, "freshness", "Older")}</span><span className="tag tag-outline">{text(story, "status", "unknown").replaceAll("_", " ")}</span><span className="eyebrow">{text(story, "lane", "Unassigned")}</span></div><h1>{text(story, "headline", "Untitled story")}</h1><p>{text(story, "summary", "Full review detail synchronized from the laptop.")}</p><div className="story-meta detailed"><span>First public <strong>{fullDateTime(story.first_public_at)} · {text(story, "age_label", "—")}</strong></span><span>Detected <strong>{fullDateTime(story.detected_at)}</strong></span><span>Trust <strong>{text(story, "trust_label", text(story, "source_trust_state", "Research required"))}</strong></span><span>Research <strong>{text(story, "research_status", "unknown").replaceAll("_", " ")}</strong></span></div></div><div className={`priority-dial priority-${priority.toLowerCase().replaceAll(" ", "-")}`}><span>Review score</span><strong>{number(story, "review_score")}</strong><small>{priority}</small></div></header>
    {text(story, "verification_notice", "") ? <section className="watch-callout"><div><span className="watch-signal" /><strong>{text(story, "verification_notice", "")}</strong></div><p>The originating publisher required automatic background research. This warning is never included in copied or exported content.</p></section> : null}
    <div className="story-layout"><div className="story-main">
      <section className="panel"><div className="panel-heading"><div><p className="section-index">01</p><h2>Ready for content</h2></div><span>{text(story, "trust_label", "Research required")}</span></div><div className="metric-grid"><div className="metric-card"><small>Organic score</small><strong>{number(story, "organic_score")}</strong><p>Calculated from importance, evidence, attention, and freshness.</p></div><div className="metric-card"><small>Urgent floor</small><strong>{story.priority_floor_applied === true ? "Applied at 80" : "Researching"}</strong><p>{text(story, "score_floor_explanation", "Priority remains evidence-bound.")}</p></div></div></section>
      <section className="panel timeline-panel"><div className="panel-heading"><div><p className="section-index">02</p><h2>Research history</h2></div><span>{records(story, "research_attempts").length} attempts</span></div>{records(story, "research_attempts").length ? <ol className="cluster-timeline">{records(story, "research_attempts").map((attempt, index) => <li key={String(attempt.id || index)}><span className="timeline-dot" /><div><small>{text(attempt, "purpose", "background") === "background" ? "Background research" : "Fresh draft search"}</small><strong>{text(attempt, "status", "Attempt").replaceAll("_", " ")} · {number(attempt, "result_count")} sources</strong><p>{text(attempt, "detail", text(attempt, "failure_reason", "Attempt queued."))}</p></div></li>)}</ol> : <p className="empty-state">Trusted-source stories do not need a background attempt. Every Create content click still starts a fresh search.</p>}</section>
      <section className="panel evidence-panel"><div className="panel-heading"><div><p className="section-index">03</p><h2>Claims</h2></div><a href={`/api/dashboard/stories/${encodeURIComponent(id)}/evidence`}>Export audit JSON</a></div><div className="claim-list">{claims.map((claim, index) => <article className="claim-row" key={String(claim.id || index)}><span className={`claim-status claim-${text(claim, "status", "unverified")}`}>{text(claim, "status", "unverified")}</span><div><p>{text(claim, "text", `Claim ${index + 1}`)}</p><small>{text(claim, "evidence_sources", "Stored source")}</small></div><span className="volatility">{text(claim, "volatility", "stable")}</span></article>)}</div></section>
      <section className="panel source-panel"><div className="panel-heading"><div><p className="section-index">04</p><h2>Source provenance</h2></div><span>{sources.length + evidence.length} stored</span></div><div className="source-list">{[...sources, ...evidence.filter((item) => text(item, "status", "confirmed") === "confirmed")].map((item, index) => <article className="source-row" key={`${String(item.id || index)}-${index}`}><div className={`source-role role-${text(item, "confirmed_role", text(item, "source_role", "discovery")).toLowerCase()}`}>{text(item, "source_provenance", "configured").replaceAll("_", " ")}</div><div className="source-copy"><h3><a href={text(item, "final_url", text(item, "canonical_url", text(item, "url", "#")))} target="_blank" rel="noreferrer">{text(item, "title", text(item, "source_name", "Source"))}</a></h3><p>{text(item, "passage", text(item, "excerpt", "Stored source evidence."))}</p><small>{text(item, "hosting_publisher_name", text(item, "source_name", "Publisher"))} · {dateTime(item.published_at)}</small></div><span className="verify-chip">{text(item, "confirmed_role", text(item, "source_role", text(item, "status")))}</span></article>)}</div></section>
      <section className="panel"><div className="panel-heading"><div><p className="section-index">05</p><h2>Decision history</h2></div><span>Audit retained</span></div><ol className="cluster-timeline">{records(story, "actions").map((action, index) => <li key={String(action.id || index)}><span className="timeline-dot" /><div><small>{fullDateTime(action.created_at)}</small><strong>{text(action, "action", "Review action").replaceAll("_", " ")}</strong><p>{text(action, "reason", "No note.")}</p></div></li>)}</ol></section>
      <StoryActions story={story} connected={Boolean(stored?.bridgeConnected)} />
    </div><aside className="story-rail"><section className="panel"><p className="section-index rail-heading">Status</p><dl className="detail-list"><div><dt>Trust</dt><dd>{text(story, "trust_label", "Research required")}</dd></div><div><dt>Research</dt><dd>{text(story, "research_status", "unknown").replaceAll("_", " ")}</dd></div><div><dt>Priority floor</dt><dd>{story.priority_floor_applied === true ? "Applied" : "Pending research"}</dd></div><div><dt>Publishing</dt><dd>Manual only</dd></div></dl></section><section className="panel"><p className="section-index rail-heading">Content history</p><div className="version-list">{records(story, "drafts").map((draft, index) => <a href={`/dashboard/drafts/${String(draft.id)}`} key={String(draft.id || index)}><span>v{String(draft.version)} · {text(draft, "status")}</span><small>{dateTime(draft.updated_at)}</small></a>)}{!records(story, "drafts").length ? <p>No content yet.</p> : null}</div></section></aside></div>
  </DashboardShell>;
}
